# Generated by Django 2.0 on 2019-10-22 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0008_partial_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='line_id',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='member',
            name='picture_url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='member',
            name='social_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_django.UserSocialAuth'),
        ),
        migrations.AddField(
            model_name='member',
            name='status_message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
