# Generated by Django 2.0 on 2019-10-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20191022_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='line_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='member',
            name='picture_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='status_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
