# Generated by Django 2.0 on 2019-10-23 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_order_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Operator')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
