# Generated by Django 2.0 on 2019-10-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20191024_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupontable',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
