# Generated by Django 2.0 on 2019-11-08 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_coupontable_used_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='member.Order'),
            preserve_default=False,
        ),
    ]
