# Generated by Django 2.0 on 2019-11-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_medicalrecord_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='text',
            new_name='detail',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='belly',
            field=models.BooleanField(default=False, verbose_name='腹'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='chest',
            field=models.BooleanField(default=False, verbose_name='胸'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='head',
            field=models.BooleanField(default=False, verbose_name='頭'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='homework',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='knees',
            field=models.BooleanField(default=False, verbose_name='膝'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='legs',
            field=models.BooleanField(default=False, verbose_name='腿'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='neck',
            field=models.BooleanField(default=False, verbose_name='頸'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='pelvis',
            field=models.BooleanField(default=False, verbose_name='骨盆'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='shoulder',
            field=models.BooleanField(default=False, verbose_name='肩'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='waist',
            field=models.BooleanField(default=False, verbose_name='腰'),
        ),
    ]
